# -*- coding: utf-8 -*-
"""02_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wVTHf4Hxb8yei9eHV1zgH9cYFxbcCG-f

# NOTE!
i used ai assistance

1) i used some of grammer/spelling Ai assistance for my comments, i have dyslexia in writting and reading, so i make a lot of misstakes in my explinations

2) in obsereving the csv and reading the data. i used claude to help me read the cloumns better and chose the most suiteable columns for my tasks
"""

from pandas import DataFrame
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from cleaning_01 import clean_data

# splitting done FIRST to prevent leakage
df = clean_data()
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

"""# • One-hot encode"""

def onehot(df):
    ohe_cols = ['MS Zoning', 'Neighborhood']
    df = pd.get_dummies(df, columns=ohe_cols, drop_first=True, dtype=int)
    return df

"""why MS_Zoning? bc Its purely nominal (no meaningful order)
different zones carry very different pricing expectations

why Neighborhood? location is one of the strongest price signals,
each of the 28 neighbourhoods has its own market dynamic

ヾ(＠⌒ー⌒＠)ノ

# • Ordinal encode
"""

# *****
def ordinal(df):
    qual_map = {'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5}
    df['Kitchen_Qual_Ord'] = df['Kitchen Qual'].map(qual_map)
    return df

"""Why Kitchen? cuz its quality has a strict ordering (Po < Fa etc..).

Ordi encoding preserves that ranking so the model treats
higher values as strictly better

# • Scale
"""

def scale(df, train_idx):
    scale_cols = ['Gr Liv Area', 'Lot Area']
    scaler = StandardScaler()

    #fit ONLY on training rows to avoid leakage
    scaler.fit(df.loc[train_idx, scale_cols])
    df[scale_cols] = scaler.transform(df[scale_cols])

    return df

"""why Gr_Liv_Area?
Gr_Liv_Area large scale can dominate
distance-based or regularised models without scaling


why Lot_Area?
Lot_Area is heavily right-skewed with outliers std
centres and normalises it

# • Create 2 domain features
"""

def domain(df):
    #A
    df['Price_Per_SqFt'] = np.where(
        df['Gr Liv Area'] > 0,
        df['SalePrice'] / df['Gr Liv Area'],
        0  # avoiding zero div
    )
    # B
    df['Total_Bathrooms'] = (
        df['Full Bath'] +
        0.5 * df['Half Bath'] +
        df['Bsmt Full Bath'].fillna(0) +
        0.5 * df['Bsmt Half Bath'].fillna(0)
    )
    return df

"""A: price per square foot (ratio)
why? normalises sale price by living area so that small and large

homes can be compared fairly, it shows location/quality premiums

B: Total bathroom count (composite)
why? buyers think in terms of total bathrooms across all floors,
one composite feature replaces four separate columns cleanly

# • Create 1 interaction feature
"""

def interaction(df):
    df['Qual_x_Area'] = df['Overall Qual'] * df['Gr Liv Area']
    return df

"""why: a large AND high quality homes command
higher prices,
multiplying quality by size captures this joint
compounding effect that neither feature encodes alone

# • Log-transform
"""

def log(df):
    skew_before = df['SalePrice'].skew()
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    fig.suptitle('saleprice  before vs after log1p transform',
                 fontsize=14, fontweight='bold')

    axes[0].hist(df['SalePrice'].dropna(), bins=50, color='#E07B54', edgecolor='white', linewidth=0.5)
    axes[0].set_title('before: SalePrice', fontsize=12)
    axes[0].set_xlabel('Sale Price ($)')
    axes[0].set_ylabel('frequency')
    axes[0].text(0.97, 0.95, f'Skewness: {skew_before:.2f}',
                 transform=axes[0].transAxes, ha='right', va='top',
                 bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    df['Log_SalePrice'] = np.log1p(df['SalePrice'])
    skew_after = df['Log_SalePrice'].skew()

    axes[1].hist(df['Log_SalePrice'].dropna(), bins=50, color='#4A90D9', edgecolor='white', linewidth=0.5)
    axes[1].set_title('after: log1p(SalePrice)', fontsize=12)
    axes[1].set_xlabel('log1p(SalePrice)')
    axes[1].set_ylabel('frequency')
    axes[1].text(0.97, 0.95, f'Skewness: {skew_after:.2f}',
                 transform=axes[1].transAxes, ha='right', va='top',
                 bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    plt.tight_layout()
    plt.show()
    print()

    return df

def log(df):
    # Before
    skew_before = df['SalePrice'].skew()

    # Apply log transform
    df['Log_SalePrice'] = np.log1p(df['SalePrice'])
    skew_after = df['Log_SalePrice'].skew()

    # Plot
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    axes[0].hist(df['SalePrice'].dropna(), bins=50)
    axes[0].set_title(f'Before (skew={skew_before:.2f})')

    axes[1].hist(df['Log_SalePrice'].dropna(), bins=50)
    axes[1].set_title(f'After (skew={skew_after:.2f})')

    plt.tight_layout()
    plt.show()
    return df

"""# • Bin

"""

def bin(df):
    df['House_Age'] = df['Yr Sold'] - df['Year Built']
    bins   = [-1, 5, 20, 50, 200]
    labels = ['New (0-5yr)', 'Recent (6-20yr)', 'Old (21-50yr)', 'Vintage (50+yr)']
    df['Age_Group'] = pd.cut(df['House_Age'], bins=bins, labels=labels)
    return df

"""why: brand new and vintage homes often command a lot, while mid-age homes not, binning lets the model captur these non linear bands easily

# • Remove redundant features
"""

def drop_corr(df, threshold=0.95):
    numeric_df = df.select_dtypes(include=[np.number]).drop(
        columns=['SalePrice', 'Log_SalePrice', 'Order', 'PID'], errors='ignore'
    )

    corr_matrix = numeric_df.corr().abs()
    upper_tri = corr_matrix.where(
        np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
    )

    high_corr_pairs = [
        (col, row, upper_tri.loc[row, col])
        for col in upper_tri.columns
        for row in upper_tri.index
        if pd.notna(upper_tri.loc[row, col]) and upper_tri.loc[row, col] > threshold
    ]
    to_drop = set()
    for col1, col2, r in sorted(high_corr_pairs, key=lambda x: -x[2]):
      to_drop.add(col2)
    #dropping the redundant columns
    df = df.drop(columns=list(to_drop), errors='ignore')
    return df

"""why: When two features have r > 0.95 they are nearly perfectly
linearly related one is almost a copy of the other

#    Combine all the functions into a one function
"""

def feature_engineering(path):
    df = clean_data()
    df = onehot(df)
    df = ordinal(df)
    df = scale(df, train_df.index)
    df = domain(df)
    df = interaction(df)
    df = log(df)
    df = bin(df)
    df = drop_corr(df)
    return df

feature_engineering(train_df).head()