# -*- coding: utf-8 -*-
"""03_eda.ipynb04_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lPiMXSnst5lfclaGDl4xADIYbkbqrWI

# NOTE!
i used ai assistance

1) i used some of grammer/spelling Ai assistance for my comments, i have dyslexia in writting and reading, so i make a lot of misstakes in my explinations

2) in obsereving the csv and reading the data. i used claude to help me read the cloumns better and chose the most suiteable columns for my tasks
"""

import pandas as pd
import numpy as np
from pandas import DataFrame
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler

import kagglehub

# Download latest version
path = kagglehub.dataset_download("prevek18/ames-housing-dataset")

print("Path to dataset files:", path)

from google.colab import files
uploaded = files.upload()
df = pd.read_csv('AmesHousing.csv')
# downloading it from kaggle cauesd error with df's so importing it form files

target = 'SalePrice'# Target variable
num_cols = df.select_dtypes(include=['number']).columns # Numerical & categorical columns
cat_cols = df.select_dtypes(include=['object']).columns
print("Numerical:", num_cols[:10])
print("Categorical:", cat_cols[:10])

"""# • Histograms"""

def features(df):
  features = ['Lot Area', 'Gr Liv Area', 'Overall Qual']

  for col in features:
      plt.figure()
      df[col].hist(bins=30)
      plt.title(f'Histogram of {col}')
      plt.xlabel(col)
      plt.ylabel('Frequency')
      plt.show()

  skew = df[col].skew()
  print(f"{col} skewness:", skew)
  return df

"""# Histograms INSIGHT
The numbers in the data set are not perfectly even, They are skewed which means they are not symmetrical, for example the LotArea variable is skewed to the right, which means that most houses are small and there are a really big houses. this tells that there are some houses that're really big and do not fit with the rest of the data. some other features like the quality of the houses are more balanced.the numbers are more spread out,
the data set is not, like what you would expect from a set of numbers, This means that we might need to change the numbers like using a log scale to make the models work better. The data set has some houses that are skewing the numbers so we need to deal with these outliers. The LotArea variable and other area-related variables are the ones that are skewed the most.

# • Grouped boxplots
"""

def cato(df):
  cato_col = 'MS Zoning'  # strong categorical feature
  df.boxplot(column=target, by=cato_col)
  plt.xticks(rotation=90)
  plt.title(f'{target}{cato_col}')
  plt.suptitle("")
  plt.show()
  return df

"""# Grouped boxplots
The boxplot shows a difference in SalePrice across different zoning categories.

Residential zones like FV and RL have higher median prices.
In contrast A or agriculture and C or commercial zones have median prices.

The spread of prices or IQR is also different across categories,
This tells us that there is a lot of variability in prices within each category.
and all this suggests that zoning classification plays a role in determining property value.

It's probably has to do with how desirable the location's the rules and regulations in place and the infrastructure available.

Zoning categories, like Residential, Agriculture and Commercial affect SalePrice.
The boxplot clearly shows that zoning classification impacts property value.

# • Correlation heatmap
"""

# Compute correlations
def corr(df):
  corr = df[num_cols].corr()[target].abs().sort_values(ascending=False)

  top_features = corr[1:11].index

  corr_matrix = df[list(top_features) + [target]].corr()

  plt.figure()
  plt.imshow(corr_matrix)
  plt.xticks(range(len(corr_matrix.columns)), corr_matrix.columns, rotation=90)
  plt.yticks(range(len(corr_matrix.columns)), corr_matrix.columns)
  plt.title("Correlation Heatmap (Top 10 Features)")
  plt.colorbar()
  plt.show()

  print(top_features)
  return df

"""The heatmap shows us that OverallQual, which is the quality of a house is the thing that is most closely related to SalePrice, this means that Overallqual is the most important feature when it comes to figuring out the SalePrice.

Other things that are also very important include how big the living area is and how big the garage is. this makes sense because when people buy a house they usually want a lot of space to live in and a big garage to park their cars.

Most of the time when these features get better the price of the house goes up. this tells us that the things that make a house good like its structure and quality are more important, than things when it comes to deciding the SalePrice of a house. the OverallQual and the living area size and the garage capacity are all very important when it comes to the SalePrice.

# Scatter plot
"""

def scatter_plot(df):
  plt.scatter(df["Gr Liv Area"], df["SalePrice"], c=df["Overall Qual"], cmap="RdYlGn", alpha=0.6)
  plt.colorbar(label="Overall Qual")
  plt.xlabel("Gr Liv Area")
  plt.ylabel("SalePrice")
  plt.title("SalePrice vs Gr Liv Area")
  plt.show()
  return df

"""The scatter plot shows a clear positive relationship between OverallQual and SalePrice: better quality homes consistently sell for more, the spread increases at higher values, indicating some variability among expensive homes. the third variable (point size) adds depth, showing that larger homes often coincide with higher

# • Groupby summary
"""

def sum(df):
  group_summary = df.groupby(cato_col)[target].mean().sort_values()

  print(group_summary)

  print("\nLowest:", group_summary.index[0])
  print("Highest:", group_summary.index[-1])
  return df

def phase_3(df):
  df = features(df)
  df = cato(df)
  df = corr(df)
  df = scatter_plot(df)
  df = sum(df)
  return df
print(phase_3(df))

"""# **Math**

# Compute mean and standard deviation
"""

#extract the target column as a NumPy array
def Compute(df):
  y = df[target].values
#Calculate the mean manually: sum of all values divided by count
  mean_y = np.sum(y) / len(y)
#calculate standard deviation: measures how spread out the values are, by subtract mean from each value then square then average then square root
  std_y = np.sqrt(np.sum((y - mean_y)**2) / len(y))

  print("mean:", mean_y)
  print("Std:", std_y)
  return df

"""# Standardise"""

def Standardise(df):
  col = 'Gr Liv Area'
  x = df[col].values
#Compute mean and standard deviation using NumPy
  mean_x = np.mean(X)
  std_x = np.std(X)
  z_manual = (X - mean_x) / std_x
  scaler = StandardScaler()
#Manual Z-score normalization: how many std deviations each value is from the mean
  z_sklearn = scaler.fit_transform(X.reshape(-1,1)).flatten()

  print("first 5:", z_manual[:5])
  print("First 5 :", z_sklearn[:5])
  print("Max differenece:", np.max(np.abs(z_manual - z_sklearn)))
  return df

"""# Compute cosine"""

#Get indices
def Compute_cos(df):
  idx_max = df[target].idxmax()
  idx_min = df[target].idxmin()
#Use numeric features only
  num_df = df.select_dtypes(include=['number']).drop(columns=[target])

#extract vectors
  v1 = num_df.loc[idx_max].values
  v2 = num_df.loc[idx_min].values

#Cosine similarity formula
  dot_product = np.dot(v1, v2)
  norm_v1 = np.linalg.norm(v1)
  norm_v2 = np.linalg.norm(v2)

  cos_sim = dot_product / (norm_v1 * norm_v2)

  print("Cosine similarity:", cos_sim)
  return df

# defining
def threshold(df):
  threshold = np.median(df[target])

  high_quality = df['Overall Qual'] >= 7
  high_price = df[target] > threshold

# conidtional probability
  prob = np.sum(high_quality & high_price) / np.sum(high_quality)

  print("Probability:", prob)
  return df

def math(df):
  df = Compute(df)
  df = Standardise(df)
  df = Compute_cos(df)
  df = threshold(df)
  return df
print(math(df))