# -*- coding: utf-8 -*-
"""01_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNthNIS5oFuSYIBcsLOeu2YXE1i203Vg

# NOTE!
i used ai assistance
1) i used some of grammer/spelling Ai assistance for my comments, i have dyslexia in writting and reading, so i make a lot of misstakes in my explinations

2) in obsereving the csv and reading the data. i used claude to help me read the cloumns better and chose the most suiteable columns for my tasks
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("prevek18/ames-housing-dataset")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""First step: Loading the csv and observing it"""

def data():
  file_ = f"{path}/AmesHousing.csv"
  df = pd.read_csv(file_)
  return df
df = data()
print(df.head())

def check_shape(df):
  print(df.shape)
check_shape(df)

"""#Inspect data types
Fixing at least 2 datatypes
"""

def fixtype(df):
  # Convert 'Sale Condition' to category type (saves memory & enables categorical operations)
  df['Sale Condition'] = df['Sale Condition'].astype('category')
  # Standardize 'Sale Type': remove extra spaces and convert to lowercase for consistency
  df['Sale Type'] = df['Sale Type'].str.strip().str.lower()
  return df

"""Checking the messing values"""

def count_missing(df):
    missing_values = df.isnull().sum()
    #df.isnull() scans every cell and marks it true if blank, False if filled
    return missing_values[missing_values > 0].sort_values(ascending=False)
    #Filters out columns that have zero missing values
def handle_missing(df):
#fill numeric columns with their median
    num_cols = df.select_dtypes(include='number').columns
    df[num_cols] = df[num_cols].fillna(df[num_cols].median())
    #fill text columns with 'Unknown'
    cato_cols = df.select_dytypes(include= 'object').columns
    df[cato_cols] = df[cato_cols].fillna('Unkown')
    return df

"""Remove dups"""

def handle_dups(df):
  #removes deplicates
  return df.drop_duplicates()

"""# Spot outliers
I'm using SalePrice column as my target
"""

def spot_outliers(df):
  #shows boxplot of SalesPrice
  plt.boxplot(df['SalePrice'])
  plt.title(['Sale price boxplot'])
  plt.show()
  return df

"""# Cap at 99th Percentile
caping extreme values at 99th percentile
"""

def cap_outliers(df):
  # calculate the 99th percentile of the 'SalePrice' column
  upper_limit = df['SalePrice'].quantile(0.99)
  #cap values above upper limit to be equal to the upper_limit using loc for coditional assignment
  #this replaces all saleprice values bigger than the upper_limit with the upper_limit itself
  df.loc[df['SalePrice'] > upper_limit, 'SalePrice'] = upper_limit
  return df

def clean_data():
  df = data()
  check_shape(df)
  df = fixtype(df)
  df = handle_missing(df)
  df = handle_dups(df)
  df = spot_outliers(df)
  df = cap_outliers(df)
  return df
df = clean_data()
print(df.head())